djfw/profiler/urls.py
from django.conf.urls import patterns, url
from .views import *
from time_selector import SetTimePeriod

urlpatterns = patterns ('',
    url(r'^reports/auditory/$', AuditoryReport.as_view(), name='auditory_report'),
    url(r'^reports/loading/$', LoadingReport.as_view(), name='loading_report'),
    url(r'^reports/browsers/$', BrowsersReport.as_view(), name='browsers_report'),
    url(r'^reports/oses/$', OsesReport.as_view(), name='oses_report'),
    url(r'^reports/modules/$', ModulesReport.as_view(), name='modules_report'),
    url(r'^reports/mobiles/$', MobilesReport.as_view(), name='mobiles_report'),
    url(r'^reports/devices/$', DevicesReport.as_view(), name='devices_report'),
    url(r'^reports/distribution/$', DistributionReport.as_view(), name='distribution_report'),
    url(r'^set_time_selector/$', SetTimePeriod.as_view(), name='set_time_selector'),

)

pm/urls.py
from django.conf.urls import patterns, url
from pm.views import *

urlpatterns = patterns('',

	url(r'^$',
		index,
		name='index'
	),
	url(r'^history/(?P<another_user_id>\d+)/$',
		history,
		name='history'
	),
	url(r'^inbox/$',
		inbox,
		name='inbox'
	),
	url(r'^outbox/$',
		outbox,
		name='outbox'
	),
	url(r'^message/(?P<message_id>\d+)$',
		message_details,
		name='message_details'
	),
	url(r'^message/create/(?P<another_user_id>\d+)/$',
		message_create,
		name='message_create'
	),
	
)

tulius/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib import admin
from tulius.views import HomeView, StatisticsView
from django.conf import settings
from tulius import forum, gameforum
from djfw.flatpages.views import FlatpagesList
from .sitemap import sitemaps
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sitemap.xml$', sitemaps_views.index, {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemaps_views.sitemap, {'sitemaps': sitemaps}, name='sitemaps'),
    
    url(r'^accounts/', include('djfw.accounts.urls')),
    url(r'^tinymce/', include('djfw.tinymce.urls',  namespace='tinymce')),
    url(r'^wysibb/', include('djfw.wysibb.urls',  namespace='wysibb')),
    url(r'^news/', include('djfw.news.urls',  namespace='news')),
    url(r'^flatpages/$', FlatpagesList.as_view(),  name='flatpages'),
    url(r'^autocomplete/', include('djfw.autocomplete.urls',  namespace='autocomplete')),
    url(r'^bugtracker/', include('djfw.bugtracker.urls',  namespace='bugtracker')),
    url(r'^profiler/', include('djfw.profiler.urls',  namespace='profiler')),
    url(r'^installer/', include('djfw.installer.urls', namespace='installer')),
    
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^statistics/$', StatisticsView.as_view(), name='stats'),

    url(r'^players/', include('tulius.players.urls', namespace='players')),
    url(r'^games/', include('tulius.games.urls',  namespace='games')),
    url(r'^forums/', include(forum.site.urls)),
    url(r'^stories/', include('tulius.stories.urls',  namespace='stories')),
    url(r'^play/', include(gameforum.site.urls)),
    
    url(r'^bugs/', include('tulius.bugs.urls',  namespace='bugs')),
    url(r'^vk/', include('tulius.vk.urls',  namespace='vk')),
    url(r'^counters/', include('tulius.counters.urls',  namespace='counters')),
)

handler404 = 'tulius.views.error404'
handler500 = 'tulius.views.error500'

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

from djfw.installer.signals import maintaince_finished, maintaince_started
from tulius.bugs.views import maint_updated
        

def set_locale(sender, **kwargs):
    import platform
    is_windows = platform.system() == 'Windows'
    if not is_windows:
        import locale
        locale.setlocale(locale.LC_ALL, 'ru_RU.UTF-8')

maintaince_finished.connect(maint_updated)
maintaince_started.connect(set_locale)

set_locale(None)

djfw/profiler/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class ProfilerMessage(models.Model):
    """
    Profiler message
    """
    class Meta:
        verbose_name = _('profiler report')
        verbose_name_plural = _('profiler reports')
        ordering = ['module_name', 'func_name', '-id']
    
    module_name = models.CharField(
        max_length=255, 
        default = '',
        blank=True,
        null=True,
        verbose_name=_('module name'),
        db_index=True,
    )
    
    func_name = models.CharField(
        max_length=255, 
        default = '',
        blank=True,
        null=True,
        verbose_name=_('function name'),
        db_index=True,
    )
    
    create_time = models.DateTimeField(
        auto_now_add    = True,
        verbose_name    = _('create time'),
        db_index=True,
    )
    
    user_id = models.BigIntegerField(
        null=True,
        blank=True,
        verbose_name=_('user')
    )
    
    exec_time = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'execution time'),
    )
    
    db_time = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'db work time'),
    )
    
    db_count = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'db requests count'),
    )
    
    template_time = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'template render time'),
    )
    
    template_db_time = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'template db work time'),
    )
    
    template_db_count = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'template db requests count'),
    )
    
    exec_param = models.BigIntegerField(
        blank=True,
        null=True,
        verbose_name=_(u'execution parameter'),
    )
    
    ip = models.IPAddressField(
        verbose_name=_('IP'),
    )
    
    browser = models.CharField(
        max_length=30, 
        default = '',
        blank=True,
        null=True,
        verbose_name=_('browser'),
    )
    
    browser_version = models.CharField(
        max_length=10, 
        default = '',
        blank=True,
        null=True,
        verbose_name=_('browser version'),
    )
    
    os = models.CharField(
        max_length=30, 
        default = '',
        blank=True,
        null=True,
        verbose_name=_('OS'),
    )
    
    os_version = models.CharField(
        max_length=10, 
        default = '',
        blank=True,
        null=True,
        verbose_name=_('OS version'),
    )
    
    device = models.CharField(
        max_length=30, 
        default = '',
        blank=True,
        null=True,
        verbose_name=_('device'),
    )
    
    mobile = models.BooleanField(
        default = False,
        blank=False,
        null=False,
        verbose_name=_('is mobile'),
    )
    
    error = models.BooleanField(
        default = False,
        blank=False,
        null=False,
        verbose_name=_('error'),
    )
    
    thread_id = models.BigIntegerField(
        blank=True,
        null=True,
        verbose_name=_(u'thread ID'),
    )
    
class TimeCollapse(models.Model):
    day = models.DateField(
        auto_now_add    = False,
        verbose_name    = _('day'),
        db_index=True,
    )
    create_time = models.DateTimeField(
        auto_now_add    = False,
        verbose_name    = _('create time'),
        db_index=True,
    )
    calls_count = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'calls count'),
    )

    anon_calls_count = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'Anonymous calls count'),
    )

    mobiles_count = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'calls count'),
    )
    
    exceptions_count = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'exceptions count'),
    )

    exec_time = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'execution time'),
    )
    
    db_time = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'db work time'),
    )
    
    db_count = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'db requests count'),
    )
    
    template_time = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'template render time'),
    )
    
    template_db_time = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'template db work time'),
    )
    
    template_db_count = models.BigIntegerField(
        blank=False,
        null=False,
        verbose_name=_(u'template db requests count'),
    )

class ClientCollapse(models.Model):
    day = models.DateField(
        auto_now_add    = False,
        verbose_name    = _('day'),
        db_index=True,
    )
    
    oses = models.TextField(
        verbose_name    = _('oses'),
    )
    browsers = models.TextField(
        verbose_name    = _('browsers'),
    )
    
    devices = models.TextField(
        verbose_name    = _('devices'),
    )
    modules = models.TextField(
        verbose_name    = _('devices'),
    )

djfw/profiler/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms

class TimeSelectorForm(forms.Form):

    weight = forms.ChoiceField(
        required = False,
        choices = [],
        label = _(u'weight'),
    )
    
    period = forms.ChoiceField(
        required = False,
        choices = [],
        label = _(u'period'),
    )

    def __init__(self, period_choices, weight_choices, *args, **kwargs):
        super(TimeSelectorForm, self).__init__(*args, **kwargs)
        self.fields['period'].choices = period_choices
        self.fields['weight'].choices = weight_choices

djfw/profiler/views.py
from django.utils.translation import ugettext_lazy as _
from .time_selector import TimePeriodView
from .graphs import sunlignt_graph, time_period_graph, time_period_graph_sum, distribution_graph
    
class AuditoryReport(TimePeriodView):
    template_name='profiler/auditory.html'
    def get_context_data(self, **kwargs):
        return {'data': time_period_graph_sum(self.request)}

class LoadingReport(TimePeriodView):
    template_name='profiler/loading.html'
    def get_context_data(self, **kwargs):
        return {'graph': time_period_graph(self.request, 'module')}

class BrowsersReport(TimePeriodView):
    template_name='profiler/sunlignt.html'
    def get_context_data(self, **kwargs):
        graph = sunlignt_graph(self.request, 'browser', 'browser_version')
        graph['name'] = _("Browsers")
        return {'graph': graph}

class OsesReport(TimePeriodView):
    template_name='profiler/sunlignt.html'
    def get_context_data(self, **kwargs):
        graph = sunlignt_graph(self.request, 'os', 'os_version')
        graph['name'] = _("Operating systems")
        return {'graph': graph}

class ModulesReport(TimePeriodView):
    template_name='profiler/sunlignt.html'
    def get_context_data(self, **kwargs):
        graph = sunlignt_graph(self.request, 'module_name', 'func_name')
        graph['name'] = _("Modules")
        graph['category_name'] = _("Module")
        graph['id'] = 'modules_call'
        for category in graph['data']:
            for elem in category['data']:
                elem['label'] = elem['name']
        return {'graph': graph}
    
class MobilesReport(TimePeriodView):
    template_name='profiler/sunlignt.html'
    def get_context_data(self, **kwargs):
        graph = sunlignt_graph(self.request, 'mobile')
        graph['name'] = _("Mobile devices")
        graph['category_name'] = _("Type")
        for category in graph['data']:
            if category['label']:
                category['label'] = _("Mobile")
            else:
                category['label'] = _("Not mobile")
        return {'graph': graph}

class DevicesReport(TimePeriodView):
    template_name='profiler/sunlignt.html'
    def get_context_data(self, **kwargs):
        graph = sunlignt_graph(self.request, 'device')
        graph['name'] = _("Devices")
        for category in graph['data']:
            if not category['label']:
                category['label'] = "-"
        return {'graph': graph}

class DistributionReport(TimePeriodView):
    template_name='profiler/distribute.html'
    def get_context_data(self, **kwargs):
        return {'data': distribution_graph(self.request)}
    

djfw/profiler/templates/profiler/snippets/sunlight_graph.html
<script type="text/javascript" src="{{ STATIC_URL }}profiler/jit/jit.js"></script>
    
<script>
    (function($) {
        {% if graph.category_subfield %}
            $( "#{{ graph.id }}_accordion" ).accordion({ collapsible: true, heightStyleType: "content" });
        {% endif %}
        
        //init data
        var json = {
            "children": [
               {% for category in graph.data %}
               {
                 "children": [
                   {% for element in category.data %}
                   {
                     "children": [], 
                     "data": {
                       "label": "<b>{{ element.label }}</b><br/>{{ element.sublabel }}",
                       "$angularWidth": {{ element.weight }}, 
                       "$color": "{% cycle "#4bb2c5" "#EAA228" "#c5b47f" "#579575" "#839557" "#958c12" "#953579" "#4b5de4" "#d8b83f" "#ff5800" "#0085cc" "#c747a3" "#cddf54" "#FBD178" "#26B4E3" "#bd70c7" %}", 
                     }, 
                     "id": "{{ element.id }}", 
                     "name": "{{ element.label }}"
                   }, 
                   {% endfor %}
                 ], 
                 "data": {
                    "label": "<b>{{ category.label }}</b></br>{{ category.sublabel }}",
                   "$color": "{% cycle "#4bb2c5" "#EAA228" "#c5b47f" "#579575" "#839557" "#958c12" "#953579" "#4b5de4" "#d8b83f" "#ff5800" "#0085cc" "#c747a3" "#cddf54" "#FBD178" "#26B4E3" "#bd70c7" %}", 
                   "$angularWidth": {{ category.weight }}, 
                 }, 
                 "id": "{{ category.id }}", 
                 "name": "{{ category.label }}"
               }, 
               {% endfor %}
            ],
            "id": "{{ graph.id }}", 
            "name": "{{ graph.name }}"
        };
        
        var labelType, useGradients, nativeTextSupport, animate;
        
        (function() {
          var ua = navigator.userAgent,
              iStuff = ua.match(/iPhone/i) || ua.match(/iPad/i),
              typeOfCanvas = typeof HTMLCanvasElement,
              nativeCanvasSupport = (typeOfCanvas == 'object' || typeOfCanvas == 'function'),
              textSupport = nativeCanvasSupport 
                && (typeof document.createElement('canvas').getContext('2d').fillText == 'function');
          //I'm setting this based on the fact that ExCanvas provides text support for IE
          //and that as of today iPhone/iPad current text support is lame
          labelType = (!nativeCanvasSupport || (textSupport && !iStuff))? 'Native' : 'HTML';
          nativeTextSupport = labelType == 'Native';
          useGradients = nativeCanvasSupport;
          animate = !(iStuff || !nativeCanvasSupport);
        })();
        
        //init Sunburst
        var sb = new $jit.Sunburst({
                //id container for the visualization
                injectInto: '{{ graph.id }}div',
                //Distance between levels
                levelDistance: 90,
                //Change node and edge styles such as
                //color, width and dimensions.
                Node: {
                  overridable: true,
                  type: useGradients? 'gradient-multipie' : 'multipie'
                },
                //Select canvas labels
                //'HTML', 'SVG' and 'Native' are possible options
                Label: {
                  type: labelType
                },
                //Change styles when hovering and clicking nodes
                NodeStyles: {
                  enable: true,
                  type: 'Native',
                  stylesClick: {
                    'color': '#33dddd'
                  },
                  stylesHover: {
                    'color': '#dd3333'
                  }
                },
                //Add tooltips
                Tips: {
                  enable: true,
                  onShow: function(tip, node) {
                    var html = ""; 
                    var data = node.data;
                    if("label" in data) {
                      html = data.label;
                    } else {
                        html = node.name;
                    }
                    html = "<div class=\"tip-title\">" + html + "</div>"; 
                    tip.innerHTML = html;
                  }
                },
                //implement event handlers
                Events: {
                  enable: true,
                  onClick: function(node) {
                    if(!node) return;
                    //hide tip
                    sb.tips.hide();
                    //rotate
                    sb.rotate(node, animate? 'animate' : 'replot', {
                      duration: 1000,
                      transition: $jit.Trans.Quart.easeInOut
                    });
                  }
                },
                // Only used when Label type is 'HTML' or 'SVG'
                // Add text to the labels. 
                // This method is only triggered on label creation
                onCreateLabel: function(domElement, node){
                  var labels = sb.config.Label.type,
                      aw = node.getData('angularWidth');
                  if (labels === 'HTML' && (node._depth < 2 || aw > 2000)) {
                    domElement.innerHTML = node.name;
                  } else if (labels === 'SVG' && (node._depth < 2 || aw > 2000)) {
                    domElement.firstChild.appendChild(document.createTextNode(node.name));
                  }
                },
                // Only used when Label type is 'HTML' or 'SVG'
                // Change node styles when labels are placed
                // or moved.
                onPlaceLabel: function(domElement, node){
                  var labels = sb.config.Label.type;
                  if (labels === 'SVG') {
                    var fch = domElement.firstChild;
                    var style = fch.style;
                    style.display = '';
                    style.cursor = 'pointer';
                    style.fontSize = "0.8em";
                    fch.setAttribute('fill', "#fff");
                  } else if (labels === 'HTML') {
                    var style = domElement.style;
                    style.display = '';
                    style.cursor = 'pointer';
                    style.fontSize = "0.8em";
                    style.color = "#ddd";
                    var left = parseInt(style.left);
                    var w = domElement.offsetWidth;
                    style.left = (left - w / 2) + 'px';
                  }
                }
           });
            //load JSON data.
            sb.loadJSON(json);
            //compute positions and plot.
            sb.refresh();
            //end
    })(jQuery);
</script>

djfw/profiler/templates/profiler/snippets/sunlight_table.html
{% load i18n %}
<table class="table">
    <thead>
        <tr>
            <th >
                {{ graph.category_name|capfirst }}
            </th>
            <th width="50px">
                {{ graph.weight_name|capfirst }}
            </th>
            <th width="50px">
                {% trans "%" %}
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{% trans "All" %}</td>
            <td>{{ graph.weight }}</td>
            <td>100%</td>
        </tr>
    </tbody>
</table>
{% if graph.category_subfield %}
    <div id="{{ graph.id }}_accordion">
        {% for category in graph.data %}
            <div>
                <table class="table wide-table module_table module_table{{forloop.counter0}}">
                    <thead>
                        <tr>
                            <th >
                                {{ category.label }}
                            </th>
                            <th width="50px">
                                {{ category.weight }}
                            </th>
                            <th width="50px">
                                {{ category.percentage|floatformat:1 }}%
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div>
                <table class="table wide-table module_table module_table{{forloop.counter0}}">
                    <tbody>
                        {% for element in category.data %}
                            <tr>
                                <td>{{ element.name }}</td>
                                <td>{{ element.percentage|floatformat:1 }}%</td>
                                <td>{{ element.weight }}</td>
                                <td>{{ element.percentage_total|floatformat:1 }}%</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endfor %}
    </div>
{% else %}
    <table class="table wide-table module_table">
        <tbody>
            {% for category in graph.data %}
                <tr>
                    <td>{{ category.label }}</td>
                    <td>{{ category.weight }}</td>
                    <td>{{ category.percentage|floatformat:1 }}%</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

djfw/profiler/templates/profiler/snippets/time_selector.html
{% load url from future %}
<script type="text/javascript" charset="utf-8">
    (function($) {
        $(document).ready(function() {
            $.ajax({
                mode: "abort",
                port: "time_selector",
                dataType: "html",
                url: "{% url 'profiler:set_time_selector' %}",
                data: {},
                success: function(data) {
                    body = $('#time_period_selector');
                    body.replaceWith(data);
                },
            });
        });
    })(jQuery);
</script>